name: liven
dependencies:
  - nomkl
  - python=2.7.12
  - pip=8.1.2
  - numpy
  - scipy
  - scikit-learn=0.18.1
  - cloudpickle
  - boto3
  - flask
  - pip:
      - wit==4.2.0
      - pathlib
      - request
      - progressbar
      - pytest-pep8
      - telepot
      - httplib2==0.9.2
      - google-api-python-client
      - oauth2client
      - spotipy
      - beautifulsoup4
      - selenium>=2.44.0,<3.0.0
      - requests
      - unidecode
      - vcrpy
      - gunicorn==19.4.5
      - itsdangerous==0.24
      - Jinja2==2.8
      - MarkupSafe==0.23
      - Werkzeug==0.11.3
      - line-bot-sdk