name: liven
dependencies:
  - nomkl
  - python=2.7.12
  - pip=8.1.2
  - numpy
  - scipy
  - scikit-learn=0.18.1
  - cloudpickle
  - boto3
  - pip:
      - wit==4.2.0
      - pathlib
      - request
      - progressbar
      - pytest-pep8
      - telepot
      - httplib2==0.9.2
      - google-api-python-client
      - oauth2client
