name: liven
dependencies:
  - python=2.7.12
  - pip=8.1.2
  - numpy
  - scipy
  - scikit-learn=0.18.1
  - cloudpickle
  - boto3
  - pip:
      - wit==4.2.0
      - git+http://github.com/mit-nlp/MITIE.git#egg=mitie
      - spacy==1.2.0
      - pathlib
      - request
      - progressbar
      - pytest-pep8
